bar/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views #Importamos las vistas de food

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('food/', include('food.urls', namespace='food')), 
    #ese food/ adelante hace que la url tenga /food antes y despues /pizza
]

food/urls.py
from django.urls import path

from . import views #el . quiere decir de esta carpeta

app_name = 'food' #food pq asi se llama nuestra app

urlpatterns = [
    path('hamburguesas/', views.hamburguesas, name="hamburguesas"),
    path('bebidas/', views.bebidas, name="bebidas"),
    path('pedido/', views.pedido, name="pedido"),
    path('exito/', views.exito, name="exito"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.logIn, name="login"),
    path('logout/', views.logOut, name="logout"),
    path('', views.index, name='index'), #chequear
    path('descuentos/', views.descuentos, name='descuentos'),
    path('historial/', views.historial, name='historial'),
    path('admin_index/', views.admin_index, name='admin_index'),
    path('ver_pedidos/', views.ver_pedidos, name='ver_pedidos'),
    path('gestionar_descuentos/', views.gestionar_descuentos, name='gestionar_descuentos'),
    path('ver_clientes/', views.ver_clientes, name='ver_clientes'),
    path('ver_solicitudes_modificacion/', views.ver_solicitudes_modificacion, name='ver_solicitudes_modificacion'),
    path('finalizar_pedido/<int:pedido_id>/', views.finalizar_pedido, name='finalizar_pedido'),
    path('desactivar_descuento/<int:descuento_id>/', views.desactivar_descuento, name='desactivar_descuento'),
    path('activar_descuento/<int:descuento_id>/', views.activar_descuento, name='activar_descuento'),
    path('eliminar_descuento/<int:descuento_id>/', views.eliminar_descuento, name='eliminar_descuento'),
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator


# Create your models here. 
# Un modelo es una clase de Python, sirve para ordenar.
# Django convierte los modelos en tablas para las BD

class Hamburguesa(models.Model):
    nombre  = models.CharField(max_length=120)
    precio1 = models.DecimalField(max_digits=10, decimal_places = 2) #2 precios 1 hamb grande otra chica
    precio2 = models.DecimalField(max_digits=10, decimal_places = 2)
    descripcion = models.CharField(max_length=500, default='')
    hImagen = models.URLField()


class Bebida(models.Model):
    nombre  = models.CharField(max_length=120)
    precioC = models.DecimalField(max_digits=8, decimal_places = 2) #2 precios 1 hamb grande otra chica
    precioG = models.DecimalField(max_digits=8, decimal_places = 2)
    descripcion = models.CharField(max_length=500, default='')
    bImagen = models.URLField() 
# Creamos migrations en la terminal
# Migrations permite convertir codigo de python en codigo sql
# python3 manage.py migrate para hacer cambios en la BD
# python3 manage.py shell usamos la consola de python para aniadir hambus


class Pedido(models.Model):
    cliente = models.ForeignKey(User, on_delete=models.CASCADE)
    mesa = models.PositiveSmallIntegerField(default=1, validators=[MaxValueValidator(30)])
    numero = models.CharField(max_length=90, unique=True)
    cuenta = models.DecimalField(max_digits=12, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    date = models.DateTimeField(auto_now_add=True, blank=True)
    note = models.TextField(blank=True, null=True)
    estado = models.CharField(max_length=20, choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo')
    
    
    def __str__(self):
        return f"Pedido #{self.numero} - Mesa: {self.mesa} - Estado: {self.estado}"

    class Meta:
        ordering = ['-date'] #Se ordenaran por fecha

   
class Item(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=120)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=90)

class Descuento(models.Model):
    nombre_descuento = models.CharField(max_length=100, default='')
    cantidad_minima = models.IntegerField(default=0)
    cantidad_maxima = models.IntegerField(default=0)
    porcentaje_descuento = models.DecimalField(max_digits=5, decimal_places=2)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre} - {self.porcentaje_descuento}% para pedidos entre {self.cantidad_minima} y {self.cantidad_maxima}"

food/forms.py
#v11
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Descuento


#Formulario Nuevo Usuario
class NewUserForm(UserCreationForm):
    email = forms.EmailField(max_length=100, required=True, help_text='Ingrese una direccion de email valida')
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']



class DescuentoForm(forms.ModelForm):
    # Definir una lista de opciones para los porcentajes
    PORCENTAJES = [(i, f"{i}%") for i in range(5, 101, 5)]  # Generar una lista de tuplas (valor, etiqueta)

    # Definir los campos del formulario
    nombre_descuento = forms.CharField(max_length=100)
    cantidad_minima = forms.IntegerField(min_value=0)
    cantidad_maxima = forms.IntegerField(min_value=0)
    porcentaje_descuento = forms.ChoiceField(choices=PORCENTAJES)

    class Meta:
        model = Descuento
        fields = ['nombre_descuento', 'cantidad_minima', 'cantidad_maxima', 'porcentaje_descuento']

    def clean(self):
        cleaned_data = super().clean()
        cantidad_minima = cleaned_data.get('cantidad_minima')
        cantidad_maxima = cleaned_data.get('cantidad_maxima')

        if cantidad_minima is not None and cantidad_maxima is not None:
            if cantidad_minima > cantidad_maxima:
                raise forms.ValidationError("La cantidad mínima debe ser menor o igual a la máxima.")

        return cleaned_data

    def save(self, commit=True):
        descuento = super().save(commit=False)
        # Realiza acciones adicionales aquí si es necesario
        if commit:
            descuento.save()
        return descuento

food/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Hamburguesa, Bebida, Pedido, Item, Descuento
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from .forms import NewUserForm, DescuentoForm
from django.contrib import messages
import random
import json
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User  # Importa el modelo de usuario correctamente


def randomOrderNumber(length): # El numero de orden sera random
    sample  = 'ABCDEFGH0123456789'
    numeroO =''.join((random.choice(sample) for i in range(length)))
    return numeroO 

# Create your views here. View es una funcion de python


# Vista de inicio para el usuario regular
def index(request):
    if request.user.is_staff:  # Verifica si el usuario es un administrador
        return admin_index(request)  # Redirige a la vista de inicio del administrador
    else:
        request.session.set_expiry(0)
        ctx = {'active_link': 'index'}
        return render(request, 'food/index.html', ctx)
#la funcion render tranfroma el codigo html a httpresponse

# Vista de inicio para el administrador
@staff_member_required
def admin_index(request):
    # Lógica para la vista de inicio del administrador
    return render(request, 'food/admin_index.html')


def hamburguesas(request):
    request.session.set_expiry(0)
    hamburguesas = Hamburguesa.objects.all()
    ctx = {'hamburguesas': hamburguesas, 'active_link':'hamburguesa'}
    return render(request, 'food/hamburguesas.html', ctx)


def bebidas(request):
    request.session.set_expiry(0)
    bebidas = Bebida.objects.all()
    ctx = {'bebidas': bebidas, 'active_link':'bebida'}
    return render(request, 'food/bebidas.html', ctx)



@csrf_exempt
def pedido(request):
    request.session.set_expiry(0)
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest': # is_ajax ya no se usa
        request.session['note'] = request.POST.get('note')  # note es el comentario
        request.session['pedido'] = request.POST.get('pedidos')
        pedidos = json.loads(request.session['pedido'])
        request.session['cuenta'] = request.POST.get('cuenta')
        mesa = request.POST.get('mesa')  # Obtener el número de mesa

        randomNum = randomOrderNumber(6)
        while Pedido.objects.filter(numero=randomNum).count() > 0:
            randomNum = randomOrderNumber(6)

        if request.user.is_authenticated:
            pedido = Pedido(
                cliente=request.user,
                numero=randomNum,
                cuenta=float(request.session['cuenta']),
                note=request.session['note'],
                mesa=mesa  # Guardar el número de mesa
            )
            pedido.save()
            request.session['pedidoNum'] = pedido.numero
            for articulo in pedidos:
                try:
                    precio_str = articulo[2].replace(',', '.')
                    precio = float(precio_str)
                    item = Item(
                        pedido=pedido,
                        nombre=articulo[0],
                        precio=precio,
                        size=articulo[1],
                    )
                    item.save()
                except ValueError as e:
                    print(f"Error al convertir el precio de '{articulo[2]}': {e}")

    mesas = list(range(1, 31))  # Lista de numeros de mesa
    ctx = {'active_link': 'pedido', 'mesas': mesas}
    return render(request, 'food/pedido.html', ctx)



#session para guardar info que son similares a local storage
# son diccionarios , tienen expire time
# 0 significa que van a expirar cuando se cierre el navegador


#Vista succes para cuando un cliente realice su orden
def exito(request):
    pedidoNum = request.session['pedidoNum']
    cuenta = request.session['cuenta'] 
    items = Item.objects.filter(pedido__numero = pedidoNum)
    pedido = get_object_or_404(Pedido, numero=pedidoNum)
    ctx = {'pedidoNum':pedidoNum, 'cuenta':cuenta, 'items':items,'pedido': pedido}
    return render(request, 'food/exito.html',ctx)


#Registrarse
def signup(request):
    ctx = {'active_link':'login'}
    if request.POST: #Significa que el usuario le envia info al server
        form = NewUserForm(request.POST)
        if form.is_valid():                       #Aqui verifica validez
            form.save()
            return redirect('index')
        else:
            ctx['form'] = form
    else:                                        #Si visita por primera vez
        form = NewUserForm()
        ctx['form'] = form
    
    return render(request, 'food/signup.html', ctx)


#Ingresar
def logIn(request):
    if request.POST:
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        user = authenticate(request, username=username, password=pwd)

        if user is not None and user.is_staff:  # Verificar si el usuario es administrador
            login(request, user)
            return redirect('food:admin_index')  # Redirigir al admin a la vista admin_index
        elif user is not None:
            login(request, user)
            return redirect('food:index')  # Redirigir a la vista index para usuarios normales
        else:
            messages.error(request, 'Usuario y/o contraseña incorrectos')

    ctx = {'active_link':'login'}
    return render(request, 'food/login.html', ctx)

def logOut(request):
    logout(request)
    return redirect('index')


def descuentos(request):
    # Lógica para la vista de descuentos
    return render(request, 'food/descuentos.html')


def historial(request):
    # Obtener todos los pedidos del usuario actual
    pedidos = Pedido.objects.filter(cliente=request.user).order_by('-date')

    # Pasar los pedidos a la plantilla
    return render(request, 'food/historial.html', {'pedidos': pedidos})


# Vista para ver todos los pedidos (solo para administrador)
@staff_member_required
def ver_pedidos(request):
    pedidos_activos = Pedido.objects.filter(estado='activo').order_by('-date')
    pedidos_finalizados = Pedido.objects.filter(estado='finalizado').order_by('-date')
    context = {'pedidos_activos': pedidos_activos, 'pedidos_finalizados': pedidos_finalizados}
    return render(request, 'food/ver_pedidos.html', context)


# Vista para gestionar descuentos (solo para administrador)
@staff_member_required
def gestionar_descuentos(request):
    if request.method == 'POST':
        form = DescuentoForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect('food:gestionar_descuentos')
    else:
        form = DescuentoForm()

    descuentos = Descuento.objects.all()
    return render(request, 'food/gestionar_descuentos.html', {'form': form, 'descuentos': descuentos})


# Vista para ver clientes (solo para administrador)
@staff_member_required
def ver_clientes(request):
    clientes = User.objects.all()
    for cliente in clientes:
        cantidad_pedidos = Pedido.objects.filter(cliente=cliente).count()
        cliente.cantidad_pedidos = cantidad_pedidos
    return render(request, 'food/ver_clientes.html', {'clientes': clientes})


# Vista para ver solicitudes de modificación (solo para administrador)
@staff_member_required
def ver_solicitudes_modificacion(request):
    # Lógica para la vista de ver solicitudes de modificación del administrador
    solicitudes = SolicitudModificacion.objects.all()
    return render(request, 'food/ver_solicitudes_modificacion.html', {'solicitudes': solicitudes})



#No muestra nada es solo para que ande el finalizar pedido de admin
def finalizar_pedido(request, pedido_id):
    pedido = get_object_or_404(Pedido, id=pedido_id)
    if request.method == 'POST':
        pedido.estado = 'finalizado'
        pedido.save()
        # Redireccionar a alguna página de confirmación o a donde sea necesario
        return redirect('food:ver_pedidos')
    # Manejar el caso en que la solicitud no sea POST (opcional)
    # Esto puede ser un error o una redirección a alguna otra página



def desactivar_descuento(request, descuento_id):
    try:
        descuento = Descuento.objects.get(pk=descuento_id)
        descuento.activo = False
        descuento.save()
    except Descuento.DoesNotExist:
        # Handle the case where the discount doesn't exist
        pass  # Or display an error message

    return redirect('food:gestionar_descuentos')

def activar_descuento(request, descuento_id):
    try:
        descuento = Descuento.objects.get(pk=descuento_id)
        descuento.activo = True
        descuento.save()
    except Descuento.DoesNotExist:
        # Handle the case where the discount doesn't exist
        pass  # Or display an error message

    return redirect('food:gestionar_descuentos')

def eliminar_descuento(request, descuento_id):
    try:
        descuento = Descuento.objects.get(pk=descuento_id)
        descuento.delete()
    except Descuento.DoesNotExist:
        # Handle the case where the discount doesn't exist
        pass  # Or display an error message

    return redirect('food:gestionar_descuentos')

food/templates/food/base.html
<!-- Codigo Reutilizable -->
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link rel="icon" type="image/png" href="https://img.icons8.com/?size=100&id=36138&format=png&color=000000">
    <title>{% block title %} {% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/fontawesome/css/all.min.css' %}">
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <script src="{% static 'food/js/main.js' %}"></script>
</head>

<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'index' %}">
            <!-- El link ese de abajo es el icono de la barra de arriba, se puede aniadir margen-->
          <img src=https://res.cloudinary.com/dwrlz7fdi/image/upload/c_crop,w_500,h_400/v1718608372/LAE_URBAN_BURGERS_2_hgwi4r.png class="logo">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynav" aria-controls="mynav"> <!-- cositas para hacerlo responsive-->
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynav">
        <!-- Links, nombres en barra de arriba -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'index' %} active {% endif %}" href="{% url 'index' %}">Menu</a> 
            <!-- solo index pq esa url ya esta definida en el proyeco -->
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'hamburguesa' %} active {% endif %}" href="{% url 'food:hamburguesas' %}">Hamburguesas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if active_link == 'bebida' %} active {% endif %}" href="{% url 'food:bebidas' %}">Bebidas</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto"> <!-- margin left que es una boostrap class para poner el carrito a la derecha -->
          {% if user.is_authenticated %} <!-- si inicio sesion -->
          <li class="nav-item mt-2">
            <h5 class="text-light pt-3 pr-4">{{ user.username }}</h5>
          </li>
          {% endif %}
          <li class="nav-item mt-2">
            <a href="{% url 'food:pedido' %}" class="nav-link {% if active_link == 'pedido' %} active {% endif %}">     <!-- v9 -->
              <img src="https://img.icons8.com/?size=35&id=15893&format=png&color=000000"><span id="carrito"></span></a>
          </li>
          {% if user.is_authenticated %} <!-- v12 -->
          <li class="nav-item">
            <a href="{% url 'food:logout' %}" class="nav-link {% if active_link == 'logout' %} active {% endif %}">
                <div class="logout-container text-center">
                    <img class="icon-margin-salir" src="https://img.icons8.com/?size=100&id=8119&format=png&color=000000" alt="Salir">
                    <div class="logout-text">Salir</div>
                </div>
            </a>
        </li>
        
        
          {% else %}
          <li class="nav-item">
            <a href="{% url 'food:login' %}" class="nav-link {% if active_link == 'login' %} active {% endif %}"> <!-- v12 -->
              <img class="icon-margin" src="https://img.icons8.com/?size=35&id=rrtYnzKMTlUr&format=png&color=000000">
              <br>Ingresar
            </a> 
          </li>
          {% endif %}
        </ul>
      </div>
      </nav>
      <div>
        {% block content %} {% endblock %}
      </div>
    <!-- jQuery library -->
    <script src="{% static 'vendor/jquery.min.js' %}"></script>
    <!-- Popper JS -->
    <script src="{% static 'vendor/popper.min.js' %}"></script>
    <!-- Latest compiled JavaScript -->
    <script src="{% static 'vendor/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <!-- Link para nuestro archivo JavaScript -->
    <script src="{% static 'food/js/main.js' %}"></script>
</body>
</html>

food/templates/food/bebidas.html
{% extends 'food/base.html' %}

{% block title %}Bebidas{% endblock %}

{% load static %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8 text-center mb-4">
      <h2 class="title">Nuestras Bebidas</h2>
      <div class="row">
        {% for bebida in bebidas %}
        <div class="col-md-4 p-4">
          <div class="bebida-item border p-3 rounded"> 
            <img class="picture img-fluid" src="{{ bebida.bImagen }}" alt="{{ bebida.nombre }}">
            <div class="card-body">
              <h4 class="pt-3" id="beb{{bebida.id}}">{{ bebida.nombre }}</h4>
              <div class="form-check-inline"> 
                <label class="form-check-label">
                  <input class="form-check-input" type="radio" name="bebida{{ bebida.id }}" value="{{ bebida.precioC }}" checked>
                  C: ${{ bebida.precioC }}
                </label>
              </div>
              <div class="form-check-inline">
                <label class="form-check-label">
                  <input class="form-check-input" type="radio" name="bebida{{ bebida.id }}" value="{{ bebida.precioG }}">
                  G: ${{ bebida.precioG }}
                </label>
              </div>
              <button class="btn btn-info mt-3" onclick="addBebida('{{ bebida.id }}')">Añadir al carrito</button>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-4 pedidos">
      <div class="bg-dark p-4 rounded text-light">
          <h2 class="text-center">Pedido</h2>
          <ul id="bcarrito"></ul> <!-- Usando #bcarrito en lugar de #pcarrito -->
          <h4 class="text-right" id="btotal">Total: $0</h4> <!-- Usando #btotal en lugar de #ptotal -->
          <a href="{% url 'food:pedido' %}" class="btn btn-pedido-carrito mt-3 w-100">Ir al Carrito</a>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'food/js/bpedido.js' %}"></script> <!-- Asegúrate de que la ruta al archivo js sea correcta -->
{% endblock %}

food/templates/food/gestionar_descuentos.html
{% extends 'food/base.html' %}

{% block title %}Gestionar Descuentos{% endblock %}

{% block content %}
<div class="container my-5">
    <h1 class="text-center">Gestionar Descuentos</h1>
    <div class="row mt-5">
        <div class="col-md-6">
            <h2>Agregar Descuento</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Agregar Descuento</button>
            </form>
        </div>
        <div class="col-md-6 d-flex flex-column">
            <h2>Descuentos Actuales</h2>
            <ul class="grid grid-cols-1 gap-2">
                {% for descuento in descuentos %}
                    <li class="p-2 border rounded bg-light">
                        <div class="d-flex flex-column align-items-start">
                            <div>
                                {{ descuento.nombre_descuento }}<br>
                                {{ descuento.porcentaje_descuento }}% de descuento
                            </div>
                            <div class="d-flex justify-content-between align-items-start">
                                {% if descuento.activo %}
                                    Activo
                                    <form method="post" action="{% url 'food:desactivar_descuento' descuento.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="des-boton btn-danger btn-sm">Desactivar</button>
                                    </form>
                                {% else %}
                                    Inactivo
                                    <form method="post" action="{% url 'food:activar_descuento' descuento.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class=" btn-success btn-sm act-boton">Activar </button>
                                    </form>
                                {% endif %}
                                <a href="{% url 'food:eliminar_descuento' descuento.id %}" class="btn btn-danger btn-sm delete-icon">
                                    <img src="https://img.icons8.com/?size=100&id=99961&format=png&color=FFFFFF" alt="Eliminar">
                                </a>
                            </div>
                        </div>
                    </li>
                    {% empty %}
                    <li class="p-2 border rounded bg-light">No hay descuentos disponibles.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %}Inicio{% endblock %}

{% load static %}

{% block content %}
<div class="container my-5">
    <h1 class="text-center">Bienvenido a LAE Urban Burgers</h1>
    

    <!-- Secciones principales -->
    <div class="row mt-5">
        <div class="col-md-4 mb-4">
            <div class="card text-center shadow-card">
                <div class="card-body">
                    <h5 class="card-title">Menú del Bar</h5>
                    <p class="card-text">Explora nuestro delicioso menú.</p>
                    <a href="{% url 'food:hamburguesas' %}" class="btn btn-coral mb-2">Ver Hamburguesas</a>
                    <a href="{% url 'food:bebidas' %}" class="btn btn-coral">Ver Bebidas</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card text-center shadow-card">
                <div class="card-body">
                    <h5 class="card-title">Descuentos</h5>
                    <p class="card-text">¡Aprovecha nuestras ofertas especiales!</p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'food:descuentos' %}" class="btn btn-coral">Ver Descuentos</a>
                    {% else %}
                    <a href="{% url 'food:login' %}" class="btn btn-coral">Ingresar</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card text-center shadow-card">
                <div class="card-body">
                    <h5 class="card-title">Historial de Pedidos</h5>
                    <p class="card-text">Revisa tus pedidos anteriores.</p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'food:historial' %}" class="btn btn-coral">Ver Historial</a>
                    {% else %}
                    <a href="{% url 'food:login' %}" class="btn btn-coral">Ingresar</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

     <!-- Noticias y Actualizaciones -->
     <div class="row mt-5">
        <div class="col-md-12">
            <h2 class="text-center">Últimas Noticias</h2>
            <p class="text-center">Mantente al día con nuestras últimas novedades y eventos especiales.</p>
            <!-- Ejemplo de noticia -->
            <div class="card mb-4 shadow-card">
                <div class="card-body">
                    <h5 class="card-title">Nueva Hamburguesa del Mes</h5>
                    <p class="card-text">Prueba nuestra nueva hamburguesa con ingredientes frescos y locales.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Testimonios -->
    <div class="row mt-5">
        <div class="col-md-12">
            <h2 class="text-center">Testimonios de Clientes</h2>
            <!-- Ejemplo de testimonio -->
            <div class="card mb-4 shadow-card">
                <div class="card-body">
                    <p class="card-text">"¡Las mejores hamburguesas que he probado! Definitivamente volveré."</p>
                    <footer class="blockquote-footer">Juan Pérez</footer>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-12 text-center">
            <h2>Contáctanos</h2>
            <p>Email: contacto@laeurbanburgers.com | Teléfono: +54 11 1234-5678</p>
            <h5>Encuéntranos en:</h5>
        </div>
        <div class="col-md-12 text-center">
            <div class="map-responsive">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2305.6882013692775!2d-64.25225698829212!3d-27.801885766654284!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x943b4df913f0ac29%3A0x6d7da993ed25f896!2sUniversidad%20Nacional%20de%20Santiago%20del%20Estero!5e0!3m2!1ses!2sar!4v1718685767965!5m2!1ses!2sar" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>

     <!-- Equipo de Desarrollo -->
     <div class="row mt-5">
        <div class="col-md-12">
            <h2 class="text-center">Equipo de Desarrollo</h2>
            <p class="text-center">Este proyecto fue desarrollado por estudiantes de la materia Ingeniería Web 2024 en la Universidad Nacional de Santiago del Estero, Facultad de Ciencias Exactas y Tecnológicas.</p>
            <div class="row mt-4">
                <div class="col-md-4 text-center">
                    <h5>Ana Paula Machado</h5>
                </div>
                <div class="col-md-4 text-center">
                    <h5>Luz Coria</h5>
                </div>
                <div class="col-md-4 text-center">
                    <h5>Eliana Proserpio</h5>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Agrega la imagen del logo -->
<img src="https://res.cloudinary.com/dwrlz7fdi/image/upload/v1718522832/WhatsApp_Image_2024-06-11_at_11.22.10_PM_preview_rev_1_wee5ii.png" alt="Logo" class="logoMenu">
{% endblock %}